name: Filippo Randon - Portfolio
favicon: null
layout_spectrum: 0.540241286624223
typography_spectrum: 0.7162663068156689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3672232355456799
  lightness: 0.137912335107103
  saturation: 0.5991462513338774
  rhythmicContrast: 0.46638381271623075
purpose: []
